# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "apache" do |apache|
    config.ssh.insert_key = false
    config.vm.hostname = "apache"
    config.vm.box = "armada/ubuntu-18.04-server-amd64"
    config.vm.box_version = "20181206.01"
    config.vm.box_check_update = false
    config.vm.network "private_network", ip: "192.168.122.5"
    config.vm.provider :libvirt do |v|
      v.memory = 1024
    end
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL 
        cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
        wget https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
        dpkg -i zabbix-release_4.0-2+bionic_all.deb
        apt update
    SHELL
    # config.vm.provision "ansible" do |ansible|
    #   #ansible.verbose = "v"
    #   ansible.limit = "all"
    #   ansible.playbook = "/etc/ansible/testplay.yml" 
    # end
  end
  
end